[package]
name = "guessing_game"
version = "0.1.0"
authors = ["[허현/서비스개발팀] <hyun2@sk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
